[project]
name = "wrist_admira"
version = "0.1.0"
description = "Wrist ADMIRA"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "torch>=2.4.0",
		"simpleitk>=2.5.2", 
    "onnxruntime>=1.22.1",
    "scipy>=1.16.2",
    "einops>=0.8.1",
    "loguru",
]
